### ISSUE TITLE
Field editor required for incollection and inproceedings?

### ISSUE THREAD

**Issue by AlexanderWillner** [Pezmc/BibLatex-Check#18]
Based on the BibLaTeX documentation the field ```editor``` is not required for ```incollection```and ```inproceedings```. However, in lines 41 and 51 they are.

**Comment by Pezmc** [comment]
Can you link to/quote the appropriate lines in the documentation? Seems like this would be a straightforward fix.

**Comment by AlexanderWillner** [comment]
Sure. See http://www.lsv.ens-cachan.fr/~markey/BibTeX/doc/ttb_en.pdf (page 13) or http://par-epistemen-taksis.de/tex-archive/macros/latex/contrib/biblatex/doc/biblatex.pdf (page 7)
