### ISSUE TITLE
Is the License MIT or AGPL?

### ISSUE THREAD

**Issue by tkw1536** [Pezmc/BibLatex-Check#25]
The [README.md](https://github.com/Pezmc/BibLatex-Check/blob/master/README.md) and [biblatex_check.py](https://github.com/Pezmc/BibLatex-Check/blob/master/biblatex_check.py) files both state the license is the MIT license. 
Yet the [LICENSE.txt](https://github.com/Pezmc/BibLatex-Check/blob/master/LICENSE.txt) document contains the license text for AGPL. 

This has me very confused. What is this project intended to be licensed under, MIT or AGPL?

**Comment by Pezmc** [comment]
Hi @tkw1536, sorry for the confusion, I've pushed an update to the license.txt.
