### ISSUE TITLE
accept journal instead of journaltitle

### ISSUE THREAD

**Issue by tommycarstensen** [Pezmc/BibLatex-Check#29]
It would be great, if I could have the script either accept `journal` as a substitute for `journaltitle` or like `pep8` have the script ignore certain types of errors. But the script was useful for bringing my bib file into shape. Thanks.

**Comment by Pezmc** [comment]
Hi @tommycarstensen, do you have a link to a biblatex specification that says you can use `journal` rather than `journaltitle. We can always add it as an alias!

**Comment by tommycarstensen** [comment]
@Pezmc It seems to be an accepted alias: https://tex.stackexchange.com/questions/87220/journaltitle-and-journal-alias-in-biblatex

**Comment by tommycarstensen** [comment]
Did you decide to accept `journal` as an alias for `journaltitle`?

**Comment by Pezmc** [comment]
If someone can open a PR I'll happily merge it!
