### ISSUE TITLE
Online service for Bibtex linting

### ISSUE THREAD

**Issue by scls19fr** [Pezmc/BibLatex-Check#33]
Hello,

it will be great if an online Bibtex checker/linter could be available.
A service comparable to https://jsonlint.com/ or http://www.yamllint.com/

Kind regards

**Comment by Pezmc** [comment]
I agree, that would be quite handy! I don't have the time to work on such a feature right now but would happily support someone who does!

**Comment by Pezmc** [comment]
Ask, and in some cases, you shall receive: https://biblatex-linter.herokuapp.com/

https://github.com/Pezmc/BibLatex-Linter

**Comment by krishnakumarg1984** [comment]
@Pezmc  Bravo. amazing effort. That was quick. In 2 hours, you fulfilled a user's request! Thank you so much for your efforts.
