### ISSUE TITLE
detect missing field terminator

### ISSUE THREAD

**Issue by alan-isaac** [Pezmc/BibLatex-Check#35]
Field values should always end with a comma.  A missing comma is not currently detected.

**Comment by lekonjak** [comment]
Hi there! Could I get assigned to solve this issue?

**Comment by Pezmc** [comment]
Sure, go for it! Please be sure to add an example of the new check in the [tests](https://github.com/Pezmc/BibLatex-Check/tree/master/tests) folder!

**Comment by Pezmc** [comment]
Fixed in #50
