### ISSUE TITLE
book entry should accept author *or* editor

### ISSUE THREAD

**Issue by alan-isaac** [Pezmc/BibLatex-Check#36]
For book entries, a missing author is flagged even if an editor is present.

**Comment by Pezmc** [comment]
Based on the [biblatex spec](http://mirrors.ibiblio.org/CTAN/macros/latex/contrib/biblatex/doc/biblatex.pdf) an author is a required field for a book.

![](http://c.pez.io/sknx/Image%202018-07-06%20at%209.34.26%20am.png)

**Comment by alan-isaac** [comment]
That's fair, but an awfully large amount of legacy .bib entries will be needlessly flagged this way.  (BibTeX used `book` where biblatex would apparently use `collection`.) How about a `--bibtex` flag to accommodate this difference?
