### ISSUE TITLE
Skipping Last Citation, Comput J invalid, school= considered invalid

### ISSUE THREAD

**Issue by Pezmc** [Pezmc/BibLatex-Check#39]
1. The last citation in a file isn't processed at all (last one should otherwise get a complaint of missing author) (#38)
2. Comput. J. isn't recognized as journal,
3. `school=`... in phdthesis gives an error if citation is NOT standalone.

```
@article{Bra78b,
   title={Pattern-based representation of chess end-game knowledge},
   author={Bratko, Ivan and Kopec, Danny and Michie, Donald},
   journal={Comput. J.},
   volume={21},
   number={2},
   pages={149--153},
   year={1978}
}

@phdthesis{Str70,
   title={Untersuchungen \"{u}ber kombinatorische Spiele},
   author={Str\"{o}hlein, Thomas},
   year={1970},
   school={TU M\"{u}nchen}
}

@misc{LOM18,
title={Lomonosov tablebases},
year={2018},
url={http://tb7.chessok.com/},
howpublished={ChessOK}
}
```

**Comment by lekonjak** [comment]
Since I was working at #35, would you mind if I take a look at this too? c;

**Comment by Pezmc** [comment]
Sure! Top work!

**Comment by Pezmc** [comment]
This was fixed in https://github.com/Pezmc/BibLatex-Check/pull/52 and https://github.com/Pezmc/BibLatex-Check/pull/50
