### ISSUE TITLE
Separate HTML from python code (read in a template)

### ISSUE THREAD

**Issue by Pezmc** [Pezmc/BibLatex-Check#4]
Separate the HTML from the python, either by reading in a template or building the html with code rather than strings

**Comment by AlexanderWillner** [comment]
http://jinja.pocoo.org/docs/dev/ seems to be a simple framework to achieve this.

**Comment by Pezmc** [comment]
This is somewhat achieved in the hosted version of this linter: https://github.com/Pezmc/BibLatex-Linter
