### ISSUE TITLE
Support for alias fields

### ISSUE THREAD

**Issue by jowens** [Pezmc/BibLatex-Check#48]
The linter flags an issue if a `@phdthesis` doesn't use `institution`, but everything I can find says `school` is in fact the right entry.

**Comment by Pezmc** [comment]
From: http://anorien.csc.warwick.ac.uk/mirrors/CTAN/macros/latex/exptl/biblatex/doc/biblatex.pdf

> phdthesis: Similar to @thesis except that the type field is optional and defaults to the
localised term ‘PhD thesis’. You may still use the type field to override that.

> thesis:  A thesis written for an educational institution to satisfy the requirements for a degree.
Use the type field to specify the type of thesis.
Required fields: author, title, type, institution, year/date
Optional fields: subtitle, titleaddon, language, note, location,
month, isbn, chapter, pages, pagetotal, addendum, pubstate, doi,
eprint, eprintclass, eprinttype, url, urldate

Further down in the document I do see:

> Traditional BibTeX uses the field name school for theses, which is supported as an
alias. See also §§ 2.2.5 and 2.3.4.

Perhaps we should add alias support?

**Comment by Pezmc** [comment]
Feature request: Add support for aliasing one field to another, e.g. in the example above, biblatex-checker would accept school as well as institution

**Comment by Pezmc** [comment]
Via email:

> Dear Pez,

> Just one minor complaint: for PhD theses, it always gives the warning that the institution is missing. But the conventional name for this field is school, not institution. I had entered the school, so should not have received a warning. Perhaps you can change the name of the field it is looking for from institution to school.

FWIW, the [pdflatex](https://mirrors.nxthost.com/ctan/macros/latex/contrib/biblatex/doc/biblatex.pdf) docs do say:

> institution list (literal)
> The name of a university or some other institution, depending on the entry type.
> Traditional BibTeX uses the field name school for theses, which is **supported as an
alias**. See also §§ 2.2.5 and 2.3.4.
